services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: payment_splitter
      POSTGRES_EXTENSIONS: uuid-ossp
    ports:
      - '5432:5432'